nodeLinker: node-modules

npmScopes:
  tjclifton:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
